#include <jabber.hpp>
#include <jabber_app.hpp>
#include <cxxopts.hpp>

#include <iostream>
#include <algorithm>
#include <regex>
#include <fstream>

using namespace jabber;
using namespace jabber_app;

int main(int argc, char *argv[])
{
   PrintBanner(std::cout);
   std::cout << "Jabber Wave Data Writer" << std::endl 
               << LINE << std::endl;

    // Option parser:
   cxxopts::Options options("jabber_out", 
      "Get CSV file of all final Wave data generated by config file.");

   options.add_options()
      ("c,config", "Config file.", cxxopts::value<std::string>())
      ("f,file", "File prefix to write (defaults 'waves').",
                        cxxopts::value<std::string>()
                        ->default_value("waves"))
      ("h,help", "Print usage information.");

   cxxopts::ParseResult result = options.parse(argc, argv);
   
   std::string args_str = result.arguments_string();
   args_str = std::regex_replace(args_str, std::regex("\n"), "\n\t");
   std::cout << "Command Line Arguments\n\t" << args_str << std::endl 
               << LINE << std::endl;

   if (result.count("help"))
   {
      std::cout << options.help() << std::endl;
      return 0;
   }
   if (result.count("config") == 0)
   {
      std::cout << "Error: no config file specified." << std::endl;
      return 1;
   }

   const std::string out_file = result["file"].as<std::string>() + ".csv";

   // Parse config file
   std::string config_file = result["config"].as<std::string>();
   TOMLConfigInput conf(config_file, &std::cout);
   std::cout << LINE << std::endl;

   // Take the dim to be the size of the freestream vector
   const int dim = conf.BaseFlow().U.size();

   // Initialize a dummy AcousticField w/ 1-point grid
   AcousticField field = InitializeAcousticField(conf, 
                                       std::vector<double>(dim,0.0),
                                       dim);
   
   // Write the Wave data
   std::ofstream os(out_file);
   WriteWaves(field.Waves(), os);

   return 0;
}
